version: '3.9'

services:
  postgres_db:
    image: postgres:14
    restart: unless-stopped
    container_name: postgres_db
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=${DUMPER_PASSWORD}
    networks:
      - db

  database_dumper_postgres:
    image: paolobasso/database_dumper:postgres-14
    restart: unless-stopped
    depends_on:
      - postgres_db
    container_name: database_dumper_postgres
    volumes:
      - ./postgres/dumps:/dumps
    environment:
      - PGID=1000
      - PUID=1000
      - DUMPER_DATABASE=mydatabase
      - DUMPER_HOST=postgres_db
      - DUMPER_USER=myuser
      - DUMPER_PASSWORD=${DUMPER_PASSWORD}
      - DUMPER_KEEP=7
      - DUMPER_SCHEDULE=0 3 * * *
      - DUMPER_HEALTHCHECKS_URL=${DUMPER_HEALTHCHECKS_URL}
    networks:
      - db

networks:
  db:
    driver: bridge
