version: '3.8'

services:
  mysql_db:
    image: mariadb:10
    restart: unless-stopped
    container_name: mysql_db
    volumes:
      - ./mysql/db:/var/lib/mariadb/data
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=${DUMPER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DUMPER_PASSWORD}
    networks:
      - db

  database_dumper_mysql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    #command: tail -f /dev/null
    #command: /dump.sh
    depends_on:
      - mysql_db
    container_name: database_dumper_mysql
    volumes:
      - ./mysql/dumps:/dumps
    environment:
      - PGID=1000
      - PUID=1000
      - DUMPER_TYPE=mysql
      - DUMPER_DATABASE=mydatabase
      - DUMPER_HOST=mysql_db
      - DUMPER_USER=myuser
      - DUMPER_PASSWORD=${DUMPER_PASSWORD}
      - DUMPER_KEEP=2
      - DUMPER_SCHEDULE=* * * * *
#      - DUMPER_HEALTHCHECKS_URL=${BACKUP_HEALTHCHECKS_URL}
    networks:
      - db

networks:
  db:
    driver: bridge
