---
name: 'build images'

on:
  push:
    branches:
      - main
    #branches-ignore:
    #  - '**'
    paths-ignore:
      - '**.md'
      - 'docker-compose.dev.yml'
      - '.env.example'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/update_dockerhub_readme.yml'
  workflow_dispatch:

jobs:
  build_publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: amd64,arm64/v8,ppc64le,s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish
        uses: docker/bake-action@v1.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          files: ./docker-bake.hcl
          pull: true
          push: true
