name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - readme.md
      - .github/workflows/update_dockerhub_readme.yml

jobs:
  update_dockerhub_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Docker Hub readme and description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./readme.md